name: Build Docker Image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
    
    - name: Install wingetcreate
      run: winget install Docker.DockerDesktop GoLang.Go --silent --accept-package-agreements --accept-source-agreements
