name: Build Docker Image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      # This action creates and boots a BuildKit-enabled builder instance.
      # It's essential for enabling BuildKit features.
      uses: docker/setup-buildx-action@v3

    - name: Set Docker context to desktop-linux
      run: docker context use desktop-linux

    - name: Run main.Go
      run: go run ./main.go
