name: Build Docker Image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v4
      
      