name: Build Docker Image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install latest Docker
      run: |
        choco install docker-desktop --pre --confirm
        Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe"
        Start-Sleep -Seconds 30

    - name: Echo Docker contexts
      run: docker context ls

    - name: Find buildx path
      run: (Get-Command docker-buildx).Source

    - name: Set Docker context to desktop-linux
      run: docker context use desktop-linux

    - name: Run main.Go
      run: go run ./main.go
 
